version: '3.8'

services:
  api:
    build:
      context: ./PixelSpaceSpringBootBackend
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}

  web:
    build: 
      context: ./PixelSpaceReactFrontend/pixel-space
      dockerfile: Dockerfile
    ports:
      - "5173:80"

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: rockit
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
